@solicitudBoletaPrepagada
Feature: Como usuario de GanaNet
  Quiero realizar solicitud de una boleta prepagada de garantía
  Para que esta sea aprobada y generada por el banco Ganadero

  @smokeTest @boletasGarantia @auto-183 @smokeTestSolicitudBoletaPrepagada @TestCaseKey=TEST-T2109
  Scenario Outline: Solicitar boleta de garantía prepagada con cuenta que solo necesita un firmante.
    Given El cliente ingresa a la pagina de gananet
      | usuario   | contrasena   |
      | <usuario> | <contrasena> |
    And Ingresa al perfil,modulo y funcionalidad correspondiente
      | perfil   | modulo   | funcionalidad   |
      | <perfil> | <modulo> | <funcionalidad> |
    When Solicita una boleta de garantía prepagada
      | personaTitular | tipoSolicitud       | cuentaOrigen    | monto   | tipoImporte    | nroTestimonio    | tipoBoleta    | ordenDe         | plazo   | enGarantiaDe     | ciudad   | oficina                | emailNotificacion       | nombre             | documento             | nombreFacturacion       | nit   |
      | <usuario>      | <tipo de solicitud> | <cuenta origen> | <monto> | <tipo importe> | <nro Testimonio> | <tipo boleta> | <a la orden de> | <plazo> | <en garantía de> | <ciudad> | <oficina de impresión> | <email de notificación> | <nombre mensajero> | <documento mensajero> | <nombre de facturación> | <nit> |
    Then Debería ver un comprobante de boleta de garantia prepagada
      | plazo   | monto   |nit  | comisionEmision        | modalInicio              | modalFinal              | mensajeDeclaracion                 |
      | <plazo> | <monto> |<nit>| <comisión por emisión> | <modal inicio solicitud> | <modal final solicitud> | <mensaje declaración y aceptación> |
    Examples:
      | usuario | contrasena | perfil           | modulo              | funcionalidad | tipo de solicitud            | cuenta origen | monto | tipo importe | nro Testimonio | tipo boleta                    | a la orden de        | plazo | en garantía de                      | ciudad | oficina de impresión | email de notificación          | nombre mensajero | documento mensajero | comisión por emisión | nombre de facturación | nit       | modal inicio solicitud                                                                                                                                                                                                                  | modal final solicitud                                                                                                                                                                       | mensaje declaración y aceptación                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
  ##@externaldata@src/test/resources/data/boletas_garantía/solicitud_boleta_prepagada_data.xlsx@HappyPath
   |245649   |1234   |Persona Juridica   |Boletas de Garantía   |Solicitudes   |Boleta de Garantía Prepagada   |1041085817   |1.00   |Bs   |254/2013   |Caución de cargos    |Choucair Testing S.A   |30   |Ejecución de obras intermunicipales    |LA PAZ    |LA PAZ (LP)    |opalaciosg@choucairtesting.com   |David Palacios   |1098738822   |450.00   |Factura Automation   |198030020   |Estimado Cliente: La solicitud podrá ser autorizada de Lunes a Viernes de 08:00 am a 23:00 pm, y serán atendida en horarios de oficina por un funcionario del Banco.   |Estimado cliente, su solicitud será registrada. Una vez se proceda a la autorización del "Firmante", un ejecutivo de negocios se contactara para que pase a recoger la Garantía solicitada.   |Declaro (declaramos) la veracidad y exactitud de los datos registrados en el presente documento liberando al Banco Ganadero S.A. de cualquier responsabilidad en relación a los mismos. Asimismo, declaro (declaramos) conocer que ante cualquier circunstancia que modifique los datos registrados en el presente me (nos) comprometo (comprometernos) a comunicar oportunamente al Banco Ganadero S.A. Así mismo declaro (declaramos) que no tengo (tenemos) ninguna vinculación con el Banco Ganadero S.A. y al grupo económico al que pertenece.\nEstoy (estamos) de acuerdo que si no entrego la documentación requerida al Banco Ganadero S.A. esta solicitud quedará sin efecto.\nAutorizo (Autorizamos) al Banco Ganadero S.A. para que obtenga información a través de los servicios de Buró de Información Crediticia, Central de Riesgos y/u otros, para conocer la situación que presento (presentamos) respecto a mis obligaciones o antecedentes financieros, tributarios, comerciales, laborales o cualquier otra información vinculada. También autorizo (autorizamos) expresamente al Banco, para que pueda intercambiar o proporcionar datos e información, incluidos datos de carácter personal y los derivados del desarrollo de la relación con el Banco o cualquier otra información, a la compañía de seguro, de cobranzas u otras personas, con la finalidad de que se facilite información o productos que puedan ser de su interés así como para obtener el buen fin de las operaciones crediticias.\nDe la misma manera, declaro (declaramos) que hemos sido debidamente informados sobre las condiciones de la garantía solicitada, las cuales acepto (aceptamos) en su totalidad en forma expresa.|
