package bo.com.bga.certificacion.gananet.utils;

public class ConstantesBD {

    public static final String QUERY_ACTUALIZACION_CLAVE = "update AUTOSRV.AUT_USUARIOS set REQ_CAMBIO_CLAVE='S',REQ_CAMBIO_CLAVE_TRANS ='S' where NRO_PERSONA =521";

    public static final String QUERY_ACTUALIZACION_CLAVE_RESET = "update AUTOSRV.AUT_USUARIOS set CLAVE_ACCESO  ='D44559F602EAB6FD62AC7680DACBFAADD13630335E951F97AF390E9DE176B6DB28512F2E0B9D4FBA5133E8B1C6E8DF59DB3A8AB9D60BE4B97CC9E81DB',CLAVE_TRANSACCIONAL ='D44559F602EAB6FD62AC7680DACBFAADD13630335E951F97AF390E9DE176B6DB28512F2E0B9D4FBA5133E8B1C6E8DF59DB3A8AB9D60BE4B97CC9E81DB' where NRO_PERSONA =521 ";

    public static final String QUERY_CLAVE_TRANSSACIONAL_SELECT = "select CLAVE_TRANSACCIONAL from AUTOSRV.AUT_USUARIOS where NRO_PERSONA =521 and CLAVE_TRANSACCIONAL= 'FA585D89C851DD338A70DCF535AA2A92FEE7836DD6AFF1226583E88E996293F16BC09C652826E0FC5C706695A03CDDCE372F139EFF4D13959DA6F1F5D3EABE'";

    public static final String QUERY_PLANILLA_ESTADO_RECHAZADO = "update GANADERO.ACH_ORDENES set ESTADO = 'RECH' where NRO_CUENTA_DES = '10150946418326' and LOTE_ORIGEN = 5552983";

    public static final String QUERY_PLANILLA_OBTENER_LOTE_POR_CONCEPTO = "SELECT * FROM SCL_CABEZAL_CREDITOS scc WHERE CONCEPTO =";

    public static final String QUERY_PLANILLA_OBTENER_DETALLE_PAGO_POR_LOTE = "SELECT * FROM SCL_DETALLE_CREDITOS sdc WHERE ESTADO = 1 AND LOTE =";

    public static final String QUERY_ADMINISTRACION_CUENTA_RELACIONADA = "UPDATE AUT_PERSONA_ROLES SET COD_ESTADO = '9' WHERE NRO_PERSONA = ";

    public static final String QUERY_TRANSFERENCIAS_MOVIMIENTOS_CONTABLES = "SELECT * FROM MOVIMIENTOS_CONTABLES mc WHERE FECHAPROCESO=TRUNC(SYSDATE) AND ";

    public static final  String QUERY_GENERACION_EXTRACTOS_NUMERO_TRANSACCION="SELECT * FROM MOVIMIENTOS_CONTABLES mc WHERE CUENTA =";

    public static final  String QUERY_SOLICITUD_CHEQUERA="SELECT * FROM AUT_MAE_TRANSACCIONES WHERE NRO_TRANSACCION=";

    public static final String QUERY_AFILIACION_CUENTA_QR="UPDATE GANADERO.CAS_QR_CUENTA SET COD_ESTADO = 2 WHERE NRO_PERSONA= ";

    public static final String QUERY_AFILIACION_CUENTA="UPDATE AUT_AFILIACION_CUENTAS SET HABILITADO = 'N' WHERE NRO_PERSONA = ";

    public static final String QUERY_COMPROBAR_AFILIACION_CUENTA="SELECT * FROM GANADERO.CAS_QR_CUENTA WHERE FECHA_MODIFICACION = TRUNC(SYSDATE) AND NRO_PERSONA = ";

    public static final String  QUERY_ACTUALIZACION_DATOS_USUARIO= "UPDATE CLI_PERSONASFISICAS SET NUMEROPUERTA='11',PISO=3,APARTAMENTO ='4',CIUDAD ='SANTA CRUZ',DEPARTAMENTO ='SANTA CRUZ',BARRIOZONA='AV BUSCH Y 3 ANILLO',TELEFONOS='78945646',EMAIL='carlos@gmail.com',CELULAR='56745282',UV=2,CALLE='PRUEBA#30-42' WHERE NUMEROPERSONAFISICA=521";

    public static final String  QUERY_ACTUALIZACION_DATOS_USUARIO_PREFERIDOS1="UPDATE CLI_REFERENCIAS_PERSONAS SET NOMBRE='ANDRES MOLINA', TELEFONOS='3561661' WHERE COD_PERSONA=521 AND TZ_LOCK = 0 AND ORDINAL = (SELECT MIN(ORDINAL) FROM CLI_REFERENCIAS_PERSONAS WHERE COD_PERSONA=521 AND TZ_LOCK = 0)";

    public static final String  QUERY_ACTUALIZACION_DATOS_USUARIO_PREFERIDOS2="UPDATE CLI_REFERENCIAS_PERSONAS SET NOMBRE='JUAN CARLOS HERNANDEZ', TELEFONOS='3561661' WHERE COD_PERSONA=521 AND TZ_LOCK = 0 AND ORDINAL = (SELECT MAX(ORDINAL) FROM CLI_REFERENCIAS_PERSONAS WHERE COD_PERSONA=521 AND TZ_LOCK = 0)";

    public static final String QUERY_DATOS_PERSONALES="SELECT * FROM CLI_PERSONASFISICAS WHERE NUMEROPERSONAFISICA=521";

    public static final String QUERY_DATOS_PREFERIDOS1="SELECT * FROM CLI_REFERENCIAS_PERSONAS WHERE COD_PERSONA=521 AND TZ_LOCK = 0 ORDER BY ORDINAL ASC FETCH FIRST 1 ROW ONLY" ;

    public static final String QUERY_DATOS_PREFERIDOS2="SELECT * FROM CLI_REFERENCIAS_PERSONAS WHERE COD_PERSONA=521 AND TZ_LOCK = 0 ORDER BY ORDINAL DESC FETCH FIRST 1 ROW ONLY";

    public static final  String QUERY_CONSULTAR_PERFILES_CREADOS="SELECT * FROM AUT_PERFILES_MENUS WHERE TRUNC(FECHA_REGISTRO)=TRUNC(SYSDATE) AND ";

    public static final  String QUERY_SOLICITUD_BOLETAS_GARANTIA="SELECT * FROM AUT_BOG_SOLICITUD WHERE FECHA_PROCESO=TRUNC(SYSDATE)";

    public static final  String QUERY_SOLICITUD_BOLETAS_GARANTIA_PARAMETROS="SELECT COUNT(*) AS RECUENTO FROM AUT_PARAMETROS_TOPAZ WHERE";

    public static final  String QUERY_REGISTRAR_RECLAMO="SELECT * FROM GANADERO.vw_wf_reclamos ORDER BY FECHA_RECLAMO DESC ,NRO_RECLAMO  DESC FETCH NEXT 1 ROWS ONLY";

    public static final  String QUERY_CONSULTAR_ORDEN_TRANSFERENCIA_OTROS_BANCOS="SELECT * FROM ACH_ORDENES WHERE FECHA_TRANSACCION= TRUNC(SYSDATE) AND";

    public static final String QUERY_ACTUALIZAR_ALIAS_CONFIGURAR_PERFIL = "UPDATE AUTOSRV.AUT_USUARIOS SET ALIAS = 'TEST' WHERE NRO_PERSONA = ";

    public static final  String QUERY_CONSULTAR_SOLICITUD_PORTA_CHEQUERA=" SELECT * FROM GANADERO.CHE_PORTACHEQUERA cp WHERE";

    public static final String QUERY_ACTUALIZAR_IMAGEN_CONFIGURAR_PERFIL = "UPDATE AUTOSRV.AUT_USUARIOS SET COD_IMAGEN_SEGURIDAD = 2 WHERE NRO_PERSONA = ";

    public static final String QUERY_CONSULTAR_CONFIGURAR_PERFIL = "SELECT * FROM AUTOSRV.AUT_USUARIOS WHERE NRO_PERSONA= ";
    public static final String QUERY_CONSULTAR_COMPROBANTE_CREDITO = "SELECT * FROM MOVIMIENTOS_CONTABLES mc WHERE CUENTA =";

    public static final String QUERY_CONSULTAR_LIMITE_TRANSACCIONES = "SELECT * FROM AUT_PERSONA_ROLES WHERE NRO_PERSONA=";

    public static final  String QUERY_ACTUALIZAR_LIMITE_TRANSACCIONES="UPDATE AUTOSRV.AUT_PERSONA_ROLES SET TRANS_DIA_PERMITIDO = 13 WHERE IDENTIFICADOR = 22572";

    public static final  String QUERY_CONSULTAR_REGISTRO_SUGERENCIAS="SELECT * FROM GANANET.PGL_DET_NOTIFICACIONES WHERE CAMPO LIKE ";

    public static final  String QUERY_CONSULTAR_HISTORICO_CHEQUERAS="SELECT * FROM CHE_CHEQSOLICITUD WHERE CUENTA= ";

    public static final  String QUERY_CONSULTAR_ORDEN_DE_COBRO_SIMPLE="SELECT NRO_CUENTA, MONTO, REFERENCIA, FECHA_VCTO FROM (SELECT NRO_CUENTA, MONTO, REFERENCIA, FECHA_VCTO, ROW_NUMBER() OVER (ORDER BY FECHA_REGISTRO DESC, HORA_REGISTRO DESC) AS rn FROM GANADERO.CAS_QR_MAESTRO WHERE NRO_CUENTA = ";

    public static final  String QUERY_CONSULTAR_CUENTA_MT940="SELECT * FROM AUT_AFIL_CTAS_EXTRACT_MT940 WHERE NRO_EMPRESA= ";

    public static final  String QUERY_ACTUALIZAR__CUENTA_MT940="UPDATE AUTOSRV.AUT_AFIL_CTAS_EXTRACT_MT940 SET HABILITADO = 'N' WHERE NRO_EMPRESA=  ";


    public static final String QUERY_CONSULTAR_CONCILIACION_CHEQUERA="SELECT * FROM CHE_CHEQUES WHERE CUENTA= ";


}
